def printAllChoices():
    print("🌐 Supported Languages:")
    languages = [
        ["en", "English"],
        ["hi", "Hindi"],
        ["es", "Spanish"],
        ["fr", "French"],
        ["de", "German"],
        ["zh-cn", "Chinese (Simplified)"],
        ["zh-tw", "Chinese (Traditional)"],
        ["ja", "Japanese"],
        ["ko", "Korean"],
        ["ru", "Russian"],
        ["ar", "Arabic"],
        ["pt", "Portuguese"],
        ["it", "Italian"],
        ["nl", "Dutch"],
        ["tr", "Turkish"],
        ["bn", "Bengali"],
        ["ur", "Urdu"],
        ["ta", "Tamil"],
        ["te", "Telugu"],
        ["gu", "Gujarati"],
        ["mr", "Marathi"],
        ["pa", "Punjabi"],
        ["ml", "Malayalam"],
        ["kn", "Kannada"],
        ["as", "Assamese"],
        ["ne", "Nepali"],
        ["si", "Sinhala"],
        ["th", "Thai"],
        ["vi", "Vietnamese"],
        ["id", "Indonesian"],
        ["ms", "Malay"],
        ["sw", "Swahili"],
        ["af", "Afrikaans"],
        ["pl", "Polish"],
        ["uk", "Ukrainian"],
        ["he", "Hebrew"],
        ["fa", "Persian (Farsi)"],
        ["ps", "Pashto"],
        ["so", "Somali"],
        ["yo", "Yoruba"],
        ["zu", "Zulu"]
    ]
    for it in languages:
        print(it[0]+ " : " + it[1])
